networks:
  turisco:
    driver: bridge

services:

  app:
    image: dockermactur/hexa:dev
    container_name: app_container
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - turisco

  db:
    image: mysql:9.2.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: on-failure
    tty: true
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zoo
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - turisco

volumes:
  database:
    driver: local