networks:
  zoonet:
    driver: bridge

services:

  proxy:
    build:
      context: ./nginx
    image: dockermactur/nginx:zoo
    container_name: proxy
    restart: on-failure
    ports:
      - "8080:443"
    environment:
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
      - ROOT_AUTH_USER=${ROOT_AUTH_USER}
      - ROOT_AUTH_PASS=${ROOT_AUTH_PASS}
    depends_on:
      app:
        condition: service_healthy
    networks:
      - zoonet

  app:
    image: dockermactur/spring:zoo
    container_name: app
    restart: on-failure
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - KEY_ALIAS=${KEY_ALIAS}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
      - ROOT_AUTH_USER=${ROOT_AUTH_USER}
      - ROOT_AUTH_PASS=${ROOT_AUTH_PASS}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - zoonet

  db:
    image: mysql:9.2.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: on-failure
    tty: true
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - zoonet

volumes:
  database:
    driver: local