version: '3.9'

networks:
  turisco:
    driver: bridge

services:
  db2:
    image: ibmcom/db2
    container_name: db2_container
    restart: always
    environment:
      DB2INST1_PASSWORD: password
#      DBNAME: zoo
      LICENSE: accept
    ports:
      - "50000:50000"
    volumes:
      - db2_data:/database/data
      - ./init-db2.sh:/docker-entrypoint-initdb.d/init-db2.sh
    privileged: true
    command: [ "/bin/bash", "/docker-entrypoint-initdb.d//init-db2.sh" ]
    healthcheck:
#      test: [ "CMD", "su", "-", "db2inst1", "-c", "db2 get db cfg for zoo || exit 1" ]
      test: [ "CMD", "su", "-", "db2inst1", "-c", "db2 list db directory || exit 1" ]
      interval: 6s
      retries: 5
      timeout: 10s
      start_period: 30s
    networks:
      - turisco

  app:
    image: hexagonal-archicture-app:latest
    container_name: app_container
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db2:
        condition: service_healthy
    restart: on-failure
    environment:
      DB2_HOST: db2
      DB2_PORT: 50000
      DB2_USER: db2inst1
      DB2_PASSWORD: password
      DB2_DATABASE: zoo
    networks:
      - turisco

volumes:
  db2_data:
    driver: local
