springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
    tryItOutEnabled: true

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO

app:
  security:
    users:
      - username: ${BASIC_AUTH_USER}
        password: ${BASIC_AUTH_PASS}
        role: USER
      - username: ${ROOT_AUTH_USER}
        password: ${ROOT_AUTH_PASS}
        role: USER,ADMIN