server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:zoo
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    url: http://localhost:8081/api-docs