spring:
  datasource:
    url: jdbc:h2:mem:zoo
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      path: /h2-console

server:
  port: 8081