#ENABLING THE SSL PROTOCOL
server:
  port: 8443
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS}

# MYSQL DATABASE
spring:
  datasource:
    url: jdbc:mysql://db:3306/zoo?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

# HEALTH CHECK
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: always

#SWAGGER
springdoc:
  swagger-ui:
    url: https://localhost:8080/api-docs